### ISSUE TITLE
Chizukeki crashes when clicking on expanded info of card_transfer

### ISSUE THREAD

**Issue by peerchemist** [PeerAssets/chizukeki#41]
![screenshot from 2018-07-17 23-02-21](https://user-images.githubusercontent.com/7818961/42845204-7eef09cc-8a15-11e8-85e9-f86e9e26a900.png)

Clicking on expanded info for this card_transfer crashes the wallet.

log:
> bundle.js:101 Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at f (bundle.js:101)
    at er (bundle.js:101)
    at h (bundle.js:101)
    at p (bundle.js:101)
    at bundle.js:101
    at s (bundle.js:101)
    at beginWork (bundle.js:101)
    at r (bundle.js:101)
    at s (bundle.js:101)
    at i (bundle.js:101)

**Comment by micimize** [comment]
Thought I had fixed this after reproduction, fixing, and redeployment, but am still seeing it in production.

**Comment by micimize** [comment]
immediately tested again and the issue is fixed 😅

**Comment by peerchemist** [comment]
Still getting this.

> bundle.js:101 Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at f (bundle.js:101)
    at er (bundle.js:101)
    at h (bundle.js:101)
    at p (bundle.js:101)
    at bundle.js:101
    at s (bundle.js:101)
    at beginWork (bundle.js:101)
    at r (bundle.js:101)
    at s (bundle.js:101)
    at i (bundle.js:101) {componentStack: "↵    in div↵    in View↵    in t↵    in Styled(t)↵…n div↵    in View↵    in div↵    in View↵    in t"}

**Comment by micimize** [comment]
fixed again in d0d5024 - actually reintroduced intentionally to test the Fallback functionality ( #4 ) and forgot to undo the changes
